// <auto-generated />
using System;
using Acme.Leasing.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Acme.Leasing.Data.EntityFramework.Migrations
{
    [DbContext(typeof(MagicLeasingContext))]
    [Migration("20260923231213_CreateLeasingTables")]
    partial class CreateLeasingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Acme.Leasing.Data.EntityFramework.Dals.ChargeDal", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<long?>("LateFeeForChargeId")
                        .HasColumnType("bigint")
                        .HasColumnName("late_fee_for_charge_id");

                    b.Property<long>("LeaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("lease_id");

                    b.Property<DateTimeOffset?>("Paid")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.HasIndex("LateFeeForChargeId");

                    b.HasIndex("LeaseId");

                    b.ToTable("charges");
                });

            modelBuilder.Entity("Acme.Leasing.Data.EntityFramework.Dals.LateFeePolicyDal", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<int>("GraceDays")
                        .HasColumnType("integer")
                        .HasColumnName("grace_days");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.ToTable("late_fee_policies");
                });

            modelBuilder.Entity("Acme.Leasing.Data.EntityFramework.Dals.LeaseDal", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_rent");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint")
                        .HasColumnName("property_id");

                    b.Property<decimal>("SecurityDeposit")
                        .HasColumnType("numeric")
                        .HasColumnName("security_deposit");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("TenantEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("tenant_email");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tenant_name");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("leases");
                });

            modelBuilder.Entity("Acme.Leasing.Data.EntityFramework.Dals.NotificationDal", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("key");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<long>("LeaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("lease_id");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("Key");

                    b.HasIndex("LeaseId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Acme.Leasing.Data.EntityFramework.Dals.PropertyDal", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.ToTable("properties");
                });

            modelBuilder.Entity("Acme.Leasing.Data.EntityFramework.Dals.ChargeDal", b =>
                {
                    b.HasOne("Acme.Leasing.Data.EntityFramework.Dals.ChargeDal", "LateFeeForCharge")
                        .WithMany()
                        .HasForeignKey("LateFeeForChargeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Acme.Leasing.Data.EntityFramework.Dals.LeaseDal", "Lease")
                        .WithMany("Charges")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LateFeeForCharge");

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("Acme.Leasing.Data.EntityFramework.Dals.LateFeePolicyDal", b =>
                {
                    b.HasOne("Acme.Leasing.Data.EntityFramework.Dals.PropertyDal", "Property")
                        .WithOne("LateFeePolicy")
                        .HasForeignKey("Acme.Leasing.Data.EntityFramework.Dals.LateFeePolicyDal", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Acme.Leasing.Data.EntityFramework.Dals.LeaseDal", b =>
                {
                    b.HasOne("Acme.Leasing.Data.EntityFramework.Dals.PropertyDal", "Property")
                        .WithMany("Leases")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Acme.Leasing.Data.EntityFramework.Dals.NotificationDal", b =>
                {
                    b.HasOne("Acme.Leasing.Data.EntityFramework.Dals.LeaseDal", "Lease")
                        .WithMany("Notifications")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("Acme.Leasing.Data.EntityFramework.Dals.LeaseDal", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Acme.Leasing.Data.EntityFramework.Dals.PropertyDal", b =>
                {
                    b.Navigation("LateFeePolicy");

                    b.Navigation("Leases");
                });
#pragma warning restore 612, 618
        }
    }
}
